export const words = [
    { spanish: "Hola", english: "Hello", italian: "Ciao", german: "Hallo" },
    { spanish: "Gracias", english: "Thank you", italian: "Grazie", german: "Danke" },
    { spanish: "Por favor", english: "Please", italian: "Per favore", german: "Bitte" },
    { spanish: "Buenos días", english: "Good morning", italian: "Buongiorno", german: "Guten Morgen" },
    { spanish: "Buenas noches", english: "Good night", italian: "Buonanotte", german: "Gute Nacht" },
    { spanish: "¿Cómo estás?", english: "How are you?", italian: "Come stai?", german: "Wie geht es dir?" },
    { spanish: "Adiós", english: "Goodbye", italian: "Arrivederci", german: "Auf Wiedersehen" },
    { spanish: "Mucho gusto", english: "Nice to meet you", italian: "Piacere di conoscerti", german: "Freut mich" },
    { spanish: "Agua", english: "Water", italian: "Acqua", german: "Wasser" },
    { spanish: "Comida", english: "Food", italian: "Cibo", german: "Essen" },
    { spanish: "Sí", english: "Yes", italian: "Sì", german: "Ja" },
    { spanish: "No", english: "No", italian: "No", german: "Nein" },
    { spanish: "Amor", english: "Love", italian: "Amore", german: "Liebe" },
    { spanish: "Familia", english: "Family", italian: "Famiglia", german: "Familie" },
    { spanish: "Casa", english: "House", italian: "Casa", german: "Haus" },
    { spanish: "Gato", english: "Cat", italian: "Gatto", german: "Katze" },
    { spanish: "Perro", english: "Dog", italian: "Cane", german: "Hund" },
    { spanish: "Amigo", english: "Friend", italian: "Amico", german: "Freund" },
    { spanish: "Tiempo", english: "Time", italian: "Tempo", german: "Zeit" },
    { spanish: "Dinero", english: "Money", italian: "Soldi", german: "Geld" },
    { spanish: "Trabajo", english: "Work", italian: "Lavoro", german: "Arbeit" },
    { spanish: "Libro", english: "Book", italian: "Libro", german: "Buch" },
    { spanish: "Mesa", english: "Table", italian: "Tavolo", german: "Tisch" },
    { spanish: "Coche", english: "Car", italian: "Macchina", german: "Auto" },
    { spanish: "Pan", english: "Bread", italian: "Pane", german: "Brot" },
    { spanish: "Leche", english: "Milk", italian: "Latte", german: "Milch" },
    { spanish: "Sol", english: "Sun", italian: "Sole", german: "Sonne" },
    { spanish: "Luna", english: "Moon", italian: "Luna", german: "Mond" },
    { spanish: "Estrella", english: "Star", italian: "Stella", german: "Stern" },
    { spanish: "Buenas tardes", english: "Good afternoon", italian: "Buon pomeriggio", german: "Guten Tag" }
];
